# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-08 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_usersession_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
