# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_tag'),
        ('tags', '0002_remove_tag_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
