# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20171214_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield'),
        ),
    ]
